@okapi = {{$dotenv OKAPIURL}}
@tenant = {{$dotenv OKAPITENANT}}
@user = {{$dotenv OKAPIUSER}}
@pwd = {{$dotenv OKAPIPWD}}
@token = {{login.response.headers.x-okapi-token}}

# @name login
POST {{okapi}}/authn/login
x-okapi-tenant: {{tenant}}
Accept: application/json
Content-Type: application/json

{
  "username":"{{user}}",
  "password":"{{pwd}}"
}

###
POST https://foliodesktools.azurewebsites.net/api/session/login
Content-Type: application/json

{
  "username":"cirkl",
  "password":"zcirkl"
}

###
GET https://foliodesktools.azurewebsites.net/api/session/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiY2lya2wifSwiaWF0IjoxNjQwMTc4NjMwLCJleHAiOjE2NDAxODU4MzB9.M9BgZ64mYb5DQC57DUUal-tHPE8v1d9Oui1ZBLZS77U

###
POST http://localhost:3000/api/session/login
Content-Type: application/json

{
  "username":"cirkl",
  "password":"zcirkl"
}

###
# GET {{okapi}}/circulation/requests?limit=100&query=((requestType="Page" and status="Open - Not yet filled")) sortby requestDate
GET {{okapi}}/circulation/requests?limit=100&query=((requestType="Recall" and status="Open - Not yet filled")) sortby requestDate
x-okapi-token: {{token}}
x-okapi-tenant: {{tenant}}
Accept: application/json

###
GET {{okapi}}/service-points
x-okapi-token: {{token}}
x-okapi-tenant: {{tenant}}
Accept: application/json

###
GET {{okapi}}/users?limit=1&query=(username="0120437400")
x-okapi-token: {{token}}
x-okapi-tenant: {{tenant}}
Accept: application/json

###
GET {{okapi}}/authn/credentials-existence?userId=3c09b69d-7e44-4f9c-b12f-73d945cf3983
x-okapi-token: {{token}}
x-okapi-tenant: {{tenant}}
Accept: application/json

###
POST {{okapi}}/authn/credentials
x-okapi-token: {{token}}
x-okapi-tenant: {{tenant}}
Accept: application/json
Content-Type: application/json

{
  "userId":"3c09b69d-7e44-4f9c-b12f-73d945cf3983",
  "password":"321321"
}

###
DELETE {{okapi}}/authn/credentials?userId=3c09b69d-7e44-4f9c-b12f-73d945cf3983
x-okapi-token: {{token}}
x-okapi-tenant: {{tenant}}
Accept: application/json

###
POST http://localhost:8080/api/session/login
Content-Type: application/json

{
  "username":"cirkl",
  "password":"zcirkl"
}

###
GET http://localhost:8080/api/user/0120437400
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiY2lya2wifSwiaWF0IjoxNjQwMDAwMjk1LCJleHAiOjE2NDAwMDc0OTV9.j47yYsl1gfoq1lx9llXr0u6j6fazEyWmyNPPrY0X2M8"